### ISSUE TITLE
Yahoo mail doesn't work. Code base is strange.

### ISSUE THREAD

**Issue by karbiv** [tikank/mailnagger#4]
Yahoo mail doesn't work. Did some exploration.
Some files use tabs for indentation, others use spaces. Though it's easy to convert in Emacs.
Imaplib2.py was copied from Python stdlib and had been patched over the years.

This chunk has 2 spaces indentation and failed to load under some conditions while debugging:

https://github.com/tikank/mailnagger/blob/723906fcc9c1ff952c8950cad93cc741e6c86c82/Mailnag/common/imaplib2.py#L1797-L1886

**Comment by tikank** [comment]
There seems to be many things. Please, give some more details.

* How does not Yahoo mail work? Does it give any errors? Is there some errors etc in log? Does connection work using "IMAP (Custom)" option? I don't have Yahoo account so I can't test it myself.
* Part of code is old and the style has been to use tabs. I generally don't like tabs in code but don't want yet do any conversion because it makes possible merges harder. I have not yet gone through Mailnag pull requests to see if there is something.
* imaplib2 is not copy of Python imaplib, it is originally from https://github.com/jazzband/imaplib2 which offers extra features, probably most notable is idle feature.
* 2 spaces indentation in imaplib2.py is not very consistent indeed, but it seems to be correct. On which conditions it fails?

**Comment by karbiv** [comment]
> * How does not Yahoo mail work? Does it give any errors?

Server returns error about password is wrong or something when using correct password.

I stumbled upon inconsistent indentation. Tabs are good if all files use tabs. PEP8 recommends that indentation must be consistent, either tabs or spaces exclusively.

**Comment by karbiv** [comment]
> * Part of code is old and the style has been to use tabs. I generally don't like tabs in code but don't want yet do any conversion because it makes possible merges harder.

Tabs are good, if all files in a code base use tabs. Otherwise editor mode must be reconfigured for a file to edit.

>2 spaces indentation in imaplib2.py is not very consistent indeed, but it seems to be correct. On which conditions it fails?

I don't remember now. I was trying to create a systemd service unit, looking at errors in journalctl. Then realized that it works perfectly from startup applications and there's no need for systemd. Debugged Yahoo mail with PDB. At some point I was getting indentation errors.

It was an exploration. Keeping Evolution mail client open suffices to be notified w/o tray indicator.
I didn't test Gnome shell tray applet because in repository it depends on original Mailnag and Vala compiler.
Cinnamon applet is easier to install.
Entertained an idea to make a ProofOC of writing applet in Python with  [Transcrypt](https://www.transcrypt.org/)  (Python to js). 

>imaplib2 is not copy of Python imaplib, it is originally from https://github.com/jazzband/imaplib2 which offers extra features, probably most notable is idle feature.

Interesting to see a Python library maintained for decades.

**Comment by tikank** [comment]
> > * How does not Yahoo mail work? Does it give any errors?
> 
> Server returns error about password is wrong or something when using correct password.

Could you copy paste mailnagger log here on error and some lines before and after the error to give some context what is happening?
Are there plugins enabled?

**Comment by karbiv** [comment]
>Could you copy paste mailnagger log here on error and some lines before and after the error to give some context what is happening?

INFO (2024-10-20 08:16:28): Successfully enabled plugin 'soundplugin'.
INFO (2024-10-20 08:16:28): Successfully enabled plugin 'libnotifyplugin'.
INFO (2024-10-20 08:16:28): Checking 5 email account(s).
ERROR (2024-10-20 08:16:37): Failed to open mailbox for account '  @yahoo.com (Yahoo)' (b'[AUTHENTICATIONFAILED] LOGIN Invalid credentials').
ERROR (2024-10-20 08:16:42): Failed to open mailbox for account '  @yahoo.com (Yahoo)' (b'[AUTHENTICATIONFAILED] LOGIN Invalid credentials').
ERROR (2024-10-20 08:16:47): Failed to open mailbox for account '  @yahoo.com (Yahoo)' (b'[AUTHENTICATIONFAILED] LOGIN Invalid credentials').
INFO (2024-10-20 08:16:47): Trying to reconnect Idler thread for account '  @yahoo.com (Yahoo)' in 5 minutes
ERROR (2024-10-20 08:16:47): Failed to open mailbox for account '  @yahoo.com (Yahoo)' (b'[AUTHENTICATIONFAILED] LOGIN Invalid credentials').
INFO (2024-10-20 08:16:47): Trying to reconnect Idler thread for account   @yahoo.com (Yahoo)' in 5 minutes


Password tested in browser, is correct.

**Comment by tikank** [comment]
Ok. That "Invalid credentials" message comes from yahoo server.
Some thoughts:

You have 5 accounts. If disable all but one Yahoo account, does it change anything?

Did the login succeeded some time before? If so, what might have been changed since?

You tested password in browser. I don't know Yahoo mail, but there is instructions to use application specific passwords for third party mail applications: https://help.yahoo.com/kb/generate-manage-rd-party-passwords-sln15241.html . Have you tried that?

**Comment by karbiv** [comment]
>Did the login succeeded some time before?

Never. Tested it anew with one account only. Same error.
It may be encoding method.

**Comment by tikank** [comment]
I tried to find more information about this.

There is a "generate app password" option in Yahoo mail settings, and using this should generate password for third party applications. **But** apparently this feature has been broken (or disabled "temporarily") at least two years.

Yahoo mail also supports some form of OAuth2 authentication, but Mailnagger does not currently support that. There is simple support to login with OAuth2 access token, but no implementation for getting and refreshing tokens.

**Comment by karbiv** [comment]
>There is a "generate app password" option in Yahoo mail settings

Gmail does it but couldn't find this app password feature on Yahoo site.
